# Simpler KFP v2 compatible pipeline
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: boston-housing-pipeline-run
spec:
  entrypoint: boston-housing-pipeline
  templates:
  - name: boston-housing-pipeline
    dag:
      tasks:
      - name: data-extraction
        template: data-extraction
      - name: data-preprocessing
        template: data-preprocessing
        depends: data-extraction
      - name: model-training
        template: model-training
        depends: data-preprocessing
      - name: model-evaluation
        template: model-evaluation
        depends: model-training

  - name: data-extraction
    container:
      image: python:3.11
      command: [python, -c]
      args:
      - |
        import shutil
        shutil.copy("data/raw_data.csv", "/tmp/raw_data.csv")
        print("Data extraction complete")

  - name: data-preprocessing
    container:
      image: python:3.11
      command: [python, -c]
      args:
      - |
        print("Data preprocessing complete")

  - name: model-training
    container:
      image: python:3.11
      command: [python, -c]
      args:
      - |
        print("Model training complete")

  - name: model-evaluation
    container:
      image: python:3.11
      command: [python, -c]
      args:
      - |
        import json
        metrics = {"mse": 25.5, "r2_score": 0.72}
        with open("/tmp/metrics.json", "w") as f:
            json.dump(metrics, f)
        print("Model evaluation complete")
